### PR TITLE
README: fix URL of rendered docs

### PR DESCRIPTION
**Pull request by willfurnass**

### CODE REVIEW

**Review by cs1jmc — APPROVED** [review]
Wonder how that ended up like that...

**Comment by willfurnass** [comment]
> The base branch requires all commits to be signed

When did we enable that?

**Comment by cs1jmc** [comment]
> > The base branch requires all commits to be signed
> 
> When did we enable that?

That's a question for @jkwmoore, however I seem to think it's always been on. I'm a good boy though, all my commits are always signed!

**Comment by willfurnass** [comment]
Amended commit with signature.

**Comment by jkwmoore** [comment]
Aye, I enabled it given: https://github.blog/changelog/2022-08-23-ssh-commit-verification-now-supported/

**Pull request merged**
